In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings

In [2]:
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

In [3]:
df = pd.read_csv(r'C:\Users\BHAVESH\IMARTICUS PYTHON TUTORIALS\INTERNSHIP PROJECTS\Analytics Vidhya SALES PREDICTION\train_sale.csv',
                 index_col=0,header=0,delimiter=' *, *')

In [4]:
df.Dependents=df.Dependents.map({'3+' : 4,'1':1,'2':2,'nan':np.nan,'0':0})

In [5]:
df_copy=pd.DataFrame.copy(df)

In [6]:
df_copy

Gender Married  Dependents     Education Self_Employed  \
Loan_ID                                                            
LP001002    Male      No         0.0      Graduate            No   
LP001003    Male     Yes         1.0      Graduate            No   
LP001005    Male     Yes         0.0      Graduate           Yes   
LP001006    Male     Yes         0.0  Not Graduate            No   
LP001008    Male      No         0.0      Graduate            No   
...          ...     ...         ...           ...           ...   
LP002978  Female      No         0.0      Graduate            No   
LP002979    Male     Yes         4.0      Graduate            No   
LP002983    Male     Yes         1.0      Graduate            No   
LP002984    Male     Yes         2.0      Graduate            No   
LP002990  Female      No         0.0      Graduate           Yes   

          ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
Loan_ID                                                                      
LP001002             5849                0.0         NaN             360.0   
LP001003             4583             1508.0       128.0             360.0   
LP001005             3000                0.0        66.0             360.0   
LP001006             2583             2358.0       120.0             360.0   
LP001008             6000                0.0       141.0             360.0   
...                   ...                ...         ...               ...   
LP002978             2900                0.0        71.0             360.0   
LP002979             4106                0.0        40.0             180.0   
LP002983             8072              240.0       253.0             360.0   
LP002984             7583                0.0       187.0             360.0   
LP002990             4583                0.0       133.0             360.0   

          Credit_History Property_Area Loan_Status  
Loan_ID                                             
LP001002             1.0         Urban           Y  
LP001003             1.0         Rural           N  
LP001005             1.0         Urban           Y  
LP001006             1.0         Urban           Y  
LP001008             1.0         Urban           Y  
...                  ...           ...         ...  
LP002978             1.0         Rural           Y  
LP002979             1.0         Rural           Y  
LP002983             1.0         Urban           Y  
LP002984             1.0         Urban           Y  
LP002990             0.0     Semiurban           N  

[614 rows x 12 columns]

In [7]:
df_copy=df_copy.drop(["Gender"],axis=1)

In [12]:
df_copy.isnull().sum()

Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [13]:
for x in df_copy.columns:
    if df_copy[x].dtype =='object' or df_copy[x].dtype == 'bool':
        df_copy[x].fillna(df_copy[x].mode()[0], inplace=True)
    if df_copy[x].dtype =='int64' or df_copy[x].dtype == 'float64':
        df_copy[x].fillna(df_copy[x].mean(), inplace=True)
"""df_copy["LoanAmount"].fillna(round(df_copy["LoanAmount"].mean(),0),
                                inplace=True)
#test_data["LoanAmount"].fillna(round(test_data["LoanAmount"].mean(),0),
                    #            inplace=True)

print(df_copy.isnull().sum())
print()
print(test_data.isnull().sum())"""

'df_copy["LoanAmount"].fillna(round(df_copy["LoanAmount"].mean(),0),\n                                inplace=True)\n#test_data["LoanAmount"].fillna(round(test_data["LoanAmount"].mean(),0),\n                    #            inplace=True)\n\nprint(df_copy.isnull().sum())\nprint()\nprint(test_data.isnull().sum())'

In [14]:
"""#imputing numerical missing data with mean value
df_copy["LoanAmount"].fillna(round(df_copy["LoanAmount"].mean(),0),
                                inplace=True)
#test_data["LoanAmount"].fillna(round(test_data["LoanAmount"].mean(),0),
                     #           inplace=True)

print(df_copy.isnull().sum())
print()
print(test_data.isnull().sum())"""

'#imputing numerical missing data with mean value\ndf_copy["LoanAmount"].fillna(round(df_copy["LoanAmount"].mean(),0),\n                                inplace=True)\n#test_data["LoanAmount"].fillna(round(test_data["LoanAmount"].mean(),0),\n                     #           inplace=True)\n\nprint(df_copy.isnull().sum())\nprint()\nprint(test_data.isnull().sum())'

In [15]:
df_copy.isnull().sum()

Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [16]:
colname=[]

for x in df_copy.columns:
    if df_copy[x].dtype=='object':
        colname.append(x)
        

In [17]:
colname

['Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status']

In [18]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    df_copy[x] =le.fit_transform(df_copy[x])

In [19]:
df_copy.head()

Married  Dependents  Education  Self_Employed  ApplicantIncome  \
Loan_ID                                                                    
LP001002        0         0.0          0              0             5849   
LP001003        1         1.0          0              0             4583   
LP001005        1         0.0          0              1             3000   
LP001006        1         0.0          1              0             2583   
LP001008        0         0.0          0              0             6000   

          CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
Loan_ID                                                                     
LP001002                0.0       146.0             360.0             1.0   
LP001003             1508.0       128.0             360.0             1.0   
LP001005                0.0        66.0             360.0             1.0   
LP001006             2358.0       120.0             360.0             1.0   
LP001008                0.0       141.0             360.0             1.0   

          Property_Area  Loan_Status  
Loan_ID                               
LP001002              2            1  
LP001003              0            0  
LP001005              2            1  
LP001006              2            1  
LP001008              2            1

In [15]:
Y = df_copy.values[:,-1]
X = df_copy.values[:,:-1]

In [16]:
print(X.shape)
print(Y.shape)

(614, 10)
(614,)


In [17]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

In [18]:
Y=Y.astype(int)

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=10)

In [20]:
X_train.shape

(460, 10)

In [21]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)

In [22]:
new_df=pd.DataFrame()
new_df["Actual"] = Y_test
new_df["Predicted"]=Y_pred

In [23]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

cfm = confusion_matrix(Y_test,Y_pred)
print(cfm)

print('Classification Report : ')

print(classification_report(Y_test,Y_pred))

acc = accuracy_score(Y_test,Y_pred)
print("Accuracy Score : ", acc)

[[ 14  27]
 [  1 112]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.93      0.34      0.50        41
           1       0.81      0.99      0.89       113

    accuracy                           0.82       154
   macro avg       0.87      0.67      0.69       154
weighted avg       0.84      0.82      0.79       154

Accuracy Score :  0.8181818181818182


In [24]:
Y_pred_prob=classifier.predict_proba(X_test)

In [25]:
Y_pred_prob

array([[0.28311917, 0.71688083],
       [0.432348  , 0.567652  ],
       [0.18409601, 0.81590399],
       [0.20749351, 0.79250649],
       [0.27095452, 0.72904548],
       [0.22412741, 0.77587259],
       [0.85912326, 0.14087674],
       [0.15225562, 0.84774438],
       [0.17539657, 0.82460343],
       [0.20276432, 0.79723568],
       [0.19927658, 0.80072342],
       [0.16999802, 0.83000198],
       [0.12507953, 0.87492047],
       [0.17943324, 0.82056676],
       [0.93733137, 0.06266863],
       [0.3455341 , 0.6544659 ],
       [0.12690225, 0.87309775],
       [0.13301959, 0.86698041],
       [0.32274785, 0.67725215],
       [0.2310221 , 0.7689779 ],
       [0.14994256, 0.85005744],
       [0.14490796, 0.85509204],
       [0.19991814, 0.80008186],
       [0.88134154, 0.11865846],
       [0.17491462, 0.82508538],
       [0.20491567, 0.79508433],
       [0.116062  , 0.883938  ],
       [0.18383555, 0.81616445],
       [0.15168939, 0.84831061],
       [0.18764972, 0.81235028],
       [0.

In [26]:
for a in np.arange(0.4,0.61,0.01):
    predict_mine = np.where(Y_pred_prob[:,0] > a, 0, 1)
    cfm=confusion_matrix(Y_test, predict_mine)
    total_err=cfm[0,1]+cfm[1,0]
    print("Errors at threshold ", a, ":",total_err, " , type 2 error :", 
          cfm[1,0]," , type 1 error:", cfm[0,1])

Errors at threshold  0.4 : 28  , type 2 error : 2  , type 1 error: 26
Errors at threshold  0.41000000000000003 : 28  , type 2 error : 2  , type 1 error: 26
Errors at threshold  0.42000000000000004 : 28  , type 2 error : 2  , type 1 error: 26
Errors at threshold  0.43000000000000005 : 28  , type 2 error : 2  , type 1 error: 26
Errors at threshold  0.44000000000000006 : 28  , type 2 error : 1  , type 1 error: 27
Errors at threshold  0.45000000000000007 : 28  , type 2 error : 1  , type 1 error: 27
Errors at threshold  0.4600000000000001 : 28  , type 2 error : 1  , type 1 error: 27
Errors at threshold  0.4700000000000001 : 28  , type 2 error : 1  , type 1 error: 27
Errors at threshold  0.4800000000000001 : 28  , type 2 error : 1  , type 1 error: 27
Errors at threshold  0.4900000000000001 : 28  , type 2 error : 1  , type 1 error: 27
Errors at threshold  0.5000000000000001 : 28  , type 2 error : 1  , type 1 error: 27
Errors at threshold  0.5100000000000001 : 29  , type 2 error : 1  , type 1 

In [27]:
Y_test=Y_test.astype(int)

In [28]:
Y_pred_prob

array([[0.28311917, 0.71688083],
       [0.432348  , 0.567652  ],
       [0.18409601, 0.81590399],
       [0.20749351, 0.79250649],
       [0.27095452, 0.72904548],
       [0.22412741, 0.77587259],
       [0.85912326, 0.14087674],
       [0.15225562, 0.84774438],
       [0.17539657, 0.82460343],
       [0.20276432, 0.79723568],
       [0.19927658, 0.80072342],
       [0.16999802, 0.83000198],
       [0.12507953, 0.87492047],
       [0.17943324, 0.82056676],
       [0.93733137, 0.06266863],
       [0.3455341 , 0.6544659 ],
       [0.12690225, 0.87309775],
       [0.13301959, 0.86698041],
       [0.32274785, 0.67725215],
       [0.2310221 , 0.7689779 ],
       [0.14994256, 0.85005744],
       [0.14490796, 0.85509204],
       [0.19991814, 0.80008186],
       [0.88134154, 0.11865846],
       [0.17491462, 0.82508538],
       [0.20491567, 0.79508433],
       [0.116062  , 0.883938  ],
       [0.18383555, 0.81616445],
       [0.15168939, 0.84831061],
       [0.18764972, 0.81235028],
       [0.

In [29]:
y_pred_class=[]
for value in Y_pred_prob[:,0]:
    if value > 0.4:
        y_pred_class.append(0)
    else:
        y_pred_class.append(1)
print(y_pred_class)

[1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [30]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

cfm = confusion_matrix(Y_test,y_pred_class)
print(cfm)

print('Classification Report : ')

print(classification_report(Y_test,y_pred_class))

acc = accuracy_score(Y_test,y_pred_class)
print("Accuracy Score : ", acc)

[[ 15  26]
 [  2 111]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.88      0.37      0.52        41
           1       0.81      0.98      0.89       113

    accuracy                           0.82       154
   macro avg       0.85      0.67      0.70       154
weighted avg       0.83      0.82      0.79       154

Accuracy Score :  0.8181818181818182


In [31]:
"""Using cross validation

classifier=LogisticRegression()

#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv=KFold(n_splits=10,random_state=10)
#print(kfold_cv)

from sklearn.model_selection import cross_val_score
#running the model using scoring metric as accuracy
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,
                                                 y=Y_train, cv=kfold_cv)
print(kfold_cv_result)
#finding the mean
print(kfold_cv_result.mean())"""

'Using cross validation\n\nclassifier=LogisticRegression()\n\n#performing kfold_cross_validation\nfrom sklearn.model_selection import KFold\nkfold_cv=KFold(n_splits=10,random_state=10)\n#print(kfold_cv)\n\nfrom sklearn.model_selection import cross_val_score\n#running the model using scoring metric as accuracy\nkfold_cv_result=cross_val_score(estimator=classifier,X=X_train,\n                                                 y=Y_train, cv=kfold_cv)\nprint(kfold_cv_result)\n#finding the mean\nprint(kfold_cv_result.mean())'

In [32]:
"""for train_value, test_value in kfold_cv.split(X_train):
    classifier.fit(X_train[train_value], Y_train[train_value]).predict(X_train[test_value])

    
Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))"""

'for train_value, test_value in kfold_cv.split(X_train):\n    classifier.fit(X_train[train_value], Y_train[train_value]).predict(X_train[test_value])\n\n    \nY_pred=classifier.predict(X_test)\n#print(list(zip(Y_test,Y_pred)))'

In [33]:
"""from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)"""

'from sklearn.metrics import confusion_matrix, accuracy_score,classification_report\n\ncfm=confusion_matrix(Y_test,Y_pred)\nprint(cfm)\nprint()\n\n\nprint("Classification report: ")\n\nprint(classification_report(Y_test,Y_pred))\n\nacc=accuracy_score(Y_test, Y_pred)\nprint("Accuracy of the model: ",acc)'

In [34]:
test_df = pd.read_csv(r'C:\Users\BHAVESH\IMARTICUS PYTHON TUTORIALS\INTERNSHIP PROJECTS\Analytics Vidhya SALES PREDICTION\test_sale.csv',
                     index_col=0,header=0,delimiter=' *, *')

In [35]:
test_df.head()

Gender Married Dependents     Education Self_Employed  \
Loan_ID                                                          
LP001015   Male     Yes          0      Graduate            No   
LP001022   Male     Yes          1      Graduate            No   
LP001031   Male     Yes          2      Graduate            No   
LP001035   Male     Yes          2      Graduate            No   
LP001051   Male      No          0  Not Graduate            No   

          ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
Loan_ID                                                                      
LP001015             5720                  0       110.0             360.0   
LP001022             3076               1500       126.0             360.0   
LP001031             5000               1800       208.0             360.0   
LP001035             2340               2546       100.0             360.0   
LP001051             3276                  0        78.0             360.0   

          Credit_History Property_Area  
Loan_ID                                 
LP001015             1.0         Urban  
LP001022             1.0         Urban  
LP001031             1.0         Urban  
LP001035             NaN         Urban  
LP001051             1.0         Urban

In [36]:
test_df.Dependents=test_df.Dependents.map({'3+' : 4,'1':1,'2':2,'nan':np.nan,'0':0})

In [37]:
test_df=test_df.drop(["Gender"],axis=1)

In [38]:
test_df.isnull().sum()

Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [39]:
for x in test_df.columns:
    if test_df[x].dtype =='object' or test_df[x].dtype == 'bool':
        test_df[x].fillna(test_df[x].mode()[0], inplace=True)
    if test_df[x].dtype =='int64' or test_df[x].dtype == 'float64':
        test_df[x].fillna(test_df[x].mean(), inplace=True)

In [40]:
test_df.isnull().sum()

Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [41]:
colname1=[]

for x in test_df.columns:
    if test_df[x].dtype=='object':
        colname1.append(x)
colname1

['Married', 'Education', 'Self_Employed', 'Property_Area']

In [42]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname1:
    test_df[x] =le.fit_transform(test_df[x])

In [43]:
test_df.head()

Married  Dependents  Education  Self_Employed  ApplicantIncome  \
Loan_ID                                                                    
LP001015        1         0.0          0              0             5720   
LP001022        1         1.0          0              0             3076   
LP001031        1         2.0          0              0             5000   
LP001035        1         2.0          0              0             2340   
LP001051        0         0.0          1              0             3276   

          CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
Loan_ID                                                                     
LP001015                  0       110.0             360.0        1.000000   
LP001022               1500       126.0             360.0        1.000000   
LP001031               1800       208.0             360.0        1.000000   
LP001035               2546       100.0             360.0        0.825444   
LP001051                  0        78.0             360.0        1.000000   

          Property_Area  
Loan_ID                  
LP001015              2  
LP001022              2  
LP001031              2  
LP001035              2  
LP001051              2

In [44]:
X_testnew = test_df.values[:,:]

In [45]:
X_testnew = scaler.transform(X_testnew)

In [46]:
X_testnew

array([[ 0.72881553, -0.70394626, -0.52836225, ...,  0.27985054,
         0.45164045,  1.22329839],
       [ 0.72881553,  0.12610061, -0.52836225, ...,  0.27985054,
         0.45164045,  1.22329839],
       [ 0.72881553,  0.95614748, -0.52836225, ...,  0.27985054,
         0.45164045,  1.22329839],
       ...,
       [-1.37208932, -0.70394626, -0.52836225, ...,  0.27985054,
        -0.04795358, -0.04760721],
       [ 0.72881553, -0.70394626, -0.52836225, ...,  0.27985054,
         0.45164045, -1.31851281],
       [-1.37208932, -0.70394626, -0.52836225, ..., -2.51865489,
         0.45164045, -1.31851281]])

In [47]:
Y_pred_prob1=classifier.predict_proba(X_testnew)

In [48]:
Y_pred_prob1

array([[0.13367215, 0.86632785],
       [0.141323  , 0.858677  ],
       [0.14430404, 0.85569596],
       [0.2298855 , 0.7701145 ],
       [0.27920892, 0.72079108],
       [0.2523894 , 0.7476106 ],
       [0.28584378, 0.71415622],
       [0.92208117, 0.07791883],
       [0.12681326, 0.87318674],
       [0.3510933 , 0.6489067 ],
       [0.28373945, 0.71626055],
       [0.16763341, 0.83236659],
       [0.24336115, 0.75663885],
       [0.85963449, 0.14036551],
       [0.23488357, 0.76511643],
       [0.19774419, 0.80225581],
       [0.15065421, 0.84934579],
       [0.11910167, 0.88089833],
       [0.22429982, 0.77570018],
       [0.26812691, 0.73187309],
       [0.1835389 , 0.8164611 ],
       [0.20378502, 0.79621498],
       [0.20902325, 0.79097675],
       [0.29251406, 0.70748594],
       [0.20407335, 0.79592665],
       [0.98230326, 0.01769674],
       [0.22310073, 0.77689927],
       [0.18922744, 0.81077256],
       [0.25119869, 0.74880131],
       [0.23563152, 0.76436848],
       [0.

In [49]:
y_pred_class1=[]
for value in Y_pred_prob1[:,0]:
    if value > 0.4:
        y_pred_class1.append(0)
    else:
        y_pred_class1.append(1)
print(y_pred_class1)

[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 

In [50]:
test_df1 = pd.read_csv(r'C:\Users\BHAVESH\IMARTICUS PYTHON TUTORIALS\INTERNSHIP PROJECTS\Analytics Vidhya SALES PREDICTION\test_sale.csv',
                     header=0,delimiter=' *, *')

In [51]:
test_df1.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [56]:
final_data = pd.DataFrame()

In [57]:
final_data["Loan_ID"] = test_df1['Loan_ID']

In [58]:
final_data["Loan_Status"] = y_pred_class1

In [59]:
final_data

Loan_ID  Loan_Status
0    LP001015            1
1    LP001022            1
2    LP001031            1
3    LP001035            1
4    LP001051            1
..        ...          ...
362  LP002971            1
363  LP002975            1
364  LP002980            0
365  LP002986            1
366  LP002989            1

[367 rows x 2 columns]

In [61]:
final_data.to_excel("Loan Status Prediction.xlsx",header=True,index=False)